name: putnik_app
description: "A new Flutter project."
# publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  auto_route: ^10.0.1
  auto_route_generator: ^10.0.1
  get_it: ^8.0.3
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_masked_text2: ^0.9.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  http: ^1.4.0
  uuid: ^4.5.1
  intl: ^0.20.2
  dotted_border: ^2.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  # image: assets/images/splash.png
  fullscreen: true
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleToFill